name: PHP Sciter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    action "Run tests" {
        uses = "franzliedke/gh-action-php@master"
        runs = "php7.1 vendor/bin/phpunit"
    }

    steps:
      - uses: actions/checkout@v2
      - uses: franzliedke/gh-action-php@master

      - name: gtk-install
        run: sudo apt-get install libgtk-3-dev

      - name: phpsciter build
        run : phpize && ./configure && make && sudo make install

      - name: display php.ini
        run: php -i|grep php.ini

      - name: add phpsciter
        run: sudo echo "extension=phpsciter.so" >> /etc/php/7.4/cli/php.ini

      - name: php modules
        run: php -m

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
