name: PHP Sciter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: gtk-install
        run: sudo apt-get instll libgtk-3-dev

      - uses: actions/checkout@v2
      - name: phpsciter-install
        run : phpize && ./configure && make && make install


    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
